#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

mkdir  -p add_libs
cd add_libs
xerca_ver=adb-5.x
wget https://github.com/greenplum-db/gp-xerces/archive/${xerca_ver}.zip
unzip ${xerca_ver}.zip

cd gp-xerces-${xerca_ver}
mkdir build
cd build
../configure --prefix=$1
make
make install DESTDIR=$2
cd ../..

orca_ver=adb-5.x
wget https://github.com/arenadata/gporca/archive/${orca_ver}.zip
unzip ${orca_ver}.zip
cd gporca-${orca_ver}
mkdir build
cd build

cmake -GNinja -DXERCES_INCLUDE_DIR=$2/$1/include -DXERCES_LIBRARY=$2/$1/lib/libxerces-c-3.1.so -DCMAKE_INSTALL_PREFIX=$1 ../
DESTDIR=$2 ninja-build install
cd ../..

export LD_LIBRARY_PATH=$2/$1/lib:$LD_LIBRARY_PATH

cd ..
export BUILDNUMBER="${3}-${4}"
./configure --enable-pxf \
            --enable-gpperfmon \
            --enable-orca \
            --with-python \
            --with-gssapi \
            --with-krb5 \
            --with-ldap \
            --with-openssl \
            --with-libxml \
            --with-libxslt \
            --with-zstd \
            --prefix=$1 --with-includes=$2/$1/include --with-libraries=$2/$1/lib --with-python --with-perl
