#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

yum install -y json-c json-c-devel

mkdir  -p add_libs
cd add_libs
wget https://github.com/greenplum-db/gp-xerces/archive/v3.1.2-p1.zip
unzip v3.1.2-p1.zip

cd gp-xerces-3.1.2-p1/
mkdir build
cd build
../configure --prefix=$1
make
make install DESTDIR=$2
cd ../..

orca_ver=2.42.3
wget https://github.com/greenplum-db/gporca/archive/v${orca_ver}.zip
unzip v${orca_ver}.zip
cd gporca-${orca_ver}
mkdir build
cd build

cmake -GNinja -DXERCES_INCLUDE_DIR=$2/$1/include -DXERCES_LIBRARY=$2/$1/lib/libxerces-c-3.1.so -DCMAKE_INSTALL_PREFIX=$1 ../
DESTDIR=$2 ninja-build install 
cd ../..

export LD_LIBRARY_PATH=$2/$1/lib:$LD_LIBRARY_PATH

cd ..
./configure --prefix=$1 --with-includes=$2/$1/include --with-libraries=$2/$1/lib --enable-pxf
