#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xe

. `dirname $0`/bigtop.bom

if [ $HOSTTYPE = "powerpc64le" ] ; then
  git clone https://github.com/ibmsoe/phantomjs-1
  cd phantomjs-1
  export PHANTOMJS_CDNURL=https://github.com/ibmsoe/phantomjs/releases/download/2.1.1
  npm install
  export PATH=$(pwd)/bin:$PATH
  cd ..
  sed  -i "s|<nodeVersion>.*</nodeVersion>|<nodeVersion>v4.4.7</nodeVersion>|" tez-ui/pom.xml
  sed  -i "s|<npmVersion>.*</npmVersion>|<npmVersion>2.15.3</npmVersion>|" tez-ui/pom.xml
fi

BUILD_TEZ_OPTS="clean package \
-Dtar -Dhadoop.version=${HADOOP_VERSION} \
-Phadoop26 \
-DskipTests"

#mvn versions:set -DnewVersion=${TEZ_VERSION}

mvn ${BUILD_TEZ_OPTS} "$@"
